# Generated by Django 4.0.3 on 2022-03-15 11:18

import Utils.Image_dir
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Toestco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='active',
            field=models.BooleanField(default=False, verbose_name='فعال یا غیر فعال بودن'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='index_sidebar',
            field=models.BooleanField(default=False, verbose_name='نمایش در ساید بار (صفحه اول )'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='post_page',
            field=models.BooleanField(default=False, verbose_name='نمایش در پست ها(وب لاگ)'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='product',
            field=models.BooleanField(default=False, verbose_name='نمایش در لیست محصولات'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=Utils.Image_dir.model_image_directory_path, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='related_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Toestco.subjects', verbose_name='عنوان مرتبط با عکس'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='Photo',
            field=models.ImageField(null=True, upload_to=Utils.Image_dir.Subject_image_directory_path, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='description',
            field=models.TextField(verbose_name='متن کامل پست'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='عنوان'),
        ),
    ]
