# Generated by Django 3.2.12 on 2022-03-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Toestco', '0002_subjects_active_subjects_index_sidebar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'عکس', 'verbose_name_plural': 'عکس ها'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'موضوع', 'verbose_name_plural': 'موضوعات'},
        ),
    ]
