# Generated by Django 3.2.12 on 2022-05-25 23:18

import Utils.Image_dir
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toestco', '0003_auto_20220315_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to=Utils.Image_dir.Subject_image_directory_path, verbose_name='عکس'),
        ),
    ]
