# Generated by Django 3.2.12 on 2022-03-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_register', '0002_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterModelOptions(
            name='user_name',
            options={'verbose_name': 'user_2', 'verbose_name_plural': 'users_2'},
        ),
    ]
