# Generated by Django 3.2.12 on 2022-03-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('user_login_register', '0003_auto_20220315_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activate',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='user_name',
        ),
    ]
