# Generated by Django 3.2.12 on 2022-05-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_register', '0005_auto_20220330_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activate',
            field=models.BooleanField(default=False, verbose_name='فعال بودن یا نبودن کاربر'),
        ),
    ]
